development:
  adapter: postgresql
  encoding: unicode
  database: itunes_app_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
